# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dhens (Dawson Hensel)
  categories:
    - title: _Title_Here_
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"


